# Generated by Django 4.0.3 on 2022-03-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='category',
            field=models.CharField(blank=True, choices=[('School Level', 'School Level'), ('College Level', 'College Level'), ('University Level', 'University Level')], max_length=50, null=True),
        ),
    ]
